GET https://api.openweathermap.org/data/2.5/weather?lat=51.10570&lon=-114.13631&appid=392c91f29e72497d445ea857cda5cd12

###3.0
GET https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&current=temperature_2m,wind_speed_10m&hourly=temperature_2m,relative_humidity_2m,wind_speed_10m


###不要aaa
GET https://api.open-meteo.com/v1/forecast?latitude=51.10570&longitude=-114.13631&current=temperature_2m,relative_humidity_2m,wind_speed_10m